version: "3.7" # compose version

services: # containers
  
  app: # automatically become a network alias
    build: ./app
    stdin_open: true
    tty: true
    volumes: 
      - ./app:/app
    ports:
      - 5000:5000

  mysql: # auto network alias
    image: mysql:8
    command: --lower_case_table_names=1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: air_demo